// <auto-generated />
namespace _65hours.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class skill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(skill));
        
        string IMigrationMetadata.Id
        {
            get { return "201410301048384_skill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
